name: codejail-ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  codejail_ci:
    name: tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python_version: '3.11'
            docker_tag: latest

    steps:
      - uses: actions/checkout@v4
      - name: Parse custom apparmor profile
        run: sudo apparmor_parser -r -W apparmor-profiles/home.sandbox.codejail_sandbox-python3.bin.python

      - name: Build latest code changes into CI image
        run: |
          docker build -t openedx-codejail \
            --cache-to type=gha \
            --cache-from type=gha \
            --build-arg python_version=${{ matrix.python_version }} .

      - name: Run container with custom apparmor profile and codejail CI image
        run: |
          docker run --name=codejail --privileged -d --security-opt apparmor=apparmor_profile \
            openedx-codejail tail -f /dev/null

      - name: Run Non Proxy Tests
        run: docker exec -t codejail bash -c 'make clean && make test_no_proxy'

      - name: Run Proxy Tests
        run: docker exec -t codejail bash -c 'make clean && make test_proxy'

      - name: Run Quality Tests
        run: docker exec -t codejail bash -c 'make quality'
